#
# Copyright 2023-2025 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

springDataGemFireVersion=1.0.+
gemfireVersion=10.2.+
springIntegrationVersion=7.0.0-M1

springTestGemfireDockerImage=tds-gemfire-docker-dev-local.usw1.packages.broadcom.com/pivotal-gemfire/vmware-gemfire:blessed-10.2-jdk17
