#
# Copyright 2023-2026 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version=1.0.0-build.9999
springDataGemFireVersion=2.0.+
gemfireVersion=10.3.+
baseGemFireVersion=10.3
baseSpringIntegrationVersion=7.1
springIntegrationVersion=7.1.0-RC1

springTestGemfireDockerImage=gemfire/gemfire:10.3-jdk17
