#
# Copyright $originalComment.match("Copyright \(c\) VMware, Inc. (\d+)", 1, "-", $today.year)$originalComment.match("Copyright (\d+)", 1, "-", $today.year)2026 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

#
# Copyright $originalComment.match("Copyright \(c\) VMware, Inc. (\d+)", 1, "-", $today.year)$originalComment.match("Copyright (\d+)", 1, "-", $today.year)2026 Broadcom. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version=1.0.0-build.9999
baseGemFireVersion=10.3
baseSpringVersion=7.1

springTestGemfireDockerImage=gemfire/gemfire:10.3-jdk17
org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.workers.max=3
